version: '3'
services:
  dhcpd:
    image: lnls/dhcpd
    command: ["general-data"]
    volumes:
      - /storage/services/repository/docker-stacks/cons-dhcpd/data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.hostname != TA-TiRack-CO-FWSrv-1
      restart_policy:
        condition: on-failure
    networks:
      host: {}
    dns: 
      - 10.0.0.71
      - 10.0.0.72
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"

networks:
  host:
    external: true
