version: '3'
services:
  dhcpd:
    image: lnls/dhcpd
    #container_name: dhcpd
    command: ["general-data"]
    volumes:
      - /storage/services/repository/docker-stacks/cons-dhcpd/data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: always
      placement:
        constraints:
        - node.hostname != TA-TiRack-CO-FWSrv-1
    networks:
      hostnet: {}
    dns: 
      - 10.0.0.71
      - 10.0.0.72

 networks:
   hostnet:
     external: true
     name: host
