version: '3'
services:
  dhcpd:
    restart: always
    image: lnls/dhcpd
    container_name: dhcpd
    command: ["ens1f1"]
    volumes:
      - ./data:/data
    network_mode: "host"
    dns: 10.0.0.71
